Hijack with a contributor status
BrandonRomano/static-lite pull request #10
Opened 2017-02-09 01:18 UTC by hhsnopek

2017-02-09 01:40 UTC, BrandonRomano requested changes

2017-02-09 01:40 UTC, BrandonRomano commented on package.json
> +  },
Ahh you know what, this is totally going to bork all of my README line number references 😢 

Did you want to also update them?

2017-02-09 01:42 UTC, BrandonRomano commented
Also to give anyone else in the world context on this PR -- While @hhsnopek doesn't have any commits in the repo right now he's been involved largely in conversations regarding the architecture of it.

2017-02-09 02:35 UTC, hhsnopek commented on package.json
> +  },
totally just moving my lines to the bottom haha

2017-02-09 04:49 UTC, BrandonRomano commented on package.json
> +  },
Lol naw keep these at the top 😜

2017-02-09 15:37 UTC, hhsnopek commented on package.json
> +  },
haha I forgot to push the changes up last night - I'll get these up tonight!

2017-02-10 01:43 UTC, BrandonRomano approved these changes
Thank you!

2017-02-10 01:43 UTC, merged